name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或者你部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build and deploy to GitHub Pages
        run: |
          bundle exec jekyll build --source src --destination build  # 这里指明了正确的源和目标目录
          bundle exec jekyll deploy
