name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 触发条件：当推送到 master 分支时

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # 设置 Node.js 版本

      - name: Install dependencies
        run: |
          cd frontend  # 确保进入到 frontend 目录
          npm install

      - name: Build the app
        run: |
          cd frontend  # 确保构建命令在 frontend 目录中执行
          npm run build

      - name: Deploy to GitHub Pages
        run: |
          cd frontend  # 确保部署命令在 frontend 目录中执行
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # 使用 GitHub Token 进行身份验证
